# Makefile for myRaytracer
# Originally built with run.sh (2012), converted to Makefile (2026)

CXX      := g++
CXXFLAGS := -O2 -std=c++11 -MMD -MP
TARGET   := myRaytracer

# Source root
SRCDIR := raytracer

# Include directories (every subdirectory under raytracer/)
INCLUDES := $(shell find $(SRCDIR) -type d | sed 's/^/-I/')
INCLUDES += -I/usr/include/x86_64-linux-gnu/

# Libraries
LDLIBS := -ltiff -ljpeg

# Build directory
BUILDDIR := build

# Discover all .cpp source files
SRCS := $(shell find $(SRCDIR) -name '*.cpp')

# Map sources to object files in build/
OBJS := $(patsubst $(SRCDIR)/%.cpp,$(BUILDDIR)/%.o,$(SRCS))

# Dependency files generated by -MMD
DEPS := $(OBJS:.o=.d)

# Default target
all: $(TARGET)

# Link
$(TARGET): $(OBJS)
	$(CXX) $(OBJS) -o $@ $(LDLIBS)
	@echo "Built $(TARGET)"

# Compile
$(BUILDDIR)/%.o: $(SRCDIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

# Include dependency files (if they exist)
-include $(DEPS)

# Run the ray tracer
run: $(TARGET)
	./$(TARGET)

# Clean build artifacts
clean:
	rm -rf $(BUILDDIR) $(TARGET)

# Full rebuild
rebuild: clean all

.PHONY: all clean rebuild run
